
// This file has been generated by the GUI designer. Do not modify.
namespace BakeryApplication
{
	public partial class CalculatorPage
	{
		private global::Gtk.EventBox eventboxMain;

		private global::Gtk.VBox vboxMain;

		private global::Gtk.EventBox eventboxLabelCalculator;

		private global::Gtk.Alignment alignmentLabelCalculator;

		private global::Gtk.Label labelCalculator;

		private global::Gtk.HBox hboxMiddle;

		private global::Gtk.VBox vboxEntry;

		private global::Gtk.Label labelEntry;

		private global::Gtk.EventBox eventboxEntry;

		private global::Gtk.Entry entryCaseNumber;

		private global::Gtk.EventBox eventboxButtonCalculate;

		private global::Gtk.Button buttonCalculate;

		private global::Gtk.EventBox eventboxRatios;

		private global::Gtk.VBox vboxRatios;

		private global::Gtk.Alignment alignmentButtonRatios;

		private global::Gtk.EventBox eventboxButtonRatios;

		private global::Gtk.Button buttonRatios;

		private global::Gtk.Table tableRatios;

		private global::Gtk.EventBox eventboxLabelBatch;

		private global::Gtk.Label labelBatch;

		private global::Gtk.EventBox eventboxLabelDough;

		private global::Gtk.Label labelDough;

		private global::Gtk.EventBox eventboxLabelFilling;

		private global::Gtk.Label labelFilling;

		private global::Gtk.EventBox eventboxLabelPaste;

		private global::Gtk.Label labelPaste;

		private global::Gtk.EventBox eventboxBottom;

		private global::Gtk.VBox vbox7;

		private global::Gtk.Label labelResult;

		private global::Gtk.Table tableResults;

		private global::Gtk.EventBox eventbox24;

		private global::Gtk.Label label13;

		private global::Gtk.EventBox eventbox26;

		private global::Gtk.Label label14;

		private global::Gtk.EventBox eventbox28;

		private global::Gtk.Label label15;

		private global::Gtk.EventBox eventbox30;

		private global::Gtk.Label label16;

		private global::Gtk.EventBox eventbox32;

		private global::Gtk.Label labelDoughBatchResult;

		private global::Gtk.EventBox eventbox34;

		private global::Gtk.Label labelChickenResult;

		private global::Gtk.EventBox eventbox36;

		private global::Gtk.Label labelCreamCheeseResult;

		private global::Gtk.EventBox eventbox38;

		private global::Gtk.Label labelShreddedCheeseResult;

		private global::Gtk.EventBox eventboxNavigation;

		private global::Gtk.HBox hboxNavigation;

		private global::Gtk.EventBox eventboxButtonHome;

		private global::Gtk.Button buttonHome;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget BakeryApplication.CalculatorPage
			global::Stetic.BinContainer.Attach(this);
			this.Name = "BakeryApplication.CalculatorPage";
			// Container child BakeryApplication.CalculatorPage.Gtk.Container+ContainerChild
			this.eventboxMain = new global::Gtk.EventBox();
			this.eventboxMain.Name = "eventboxMain";
			// Container child eventboxMain.Gtk.Container+ContainerChild
			this.vboxMain = new global::Gtk.VBox();
			this.vboxMain.Name = "vboxMain";
			this.vboxMain.Spacing = 6;
			// Container child vboxMain.Gtk.Box+BoxChild
			this.eventboxLabelCalculator = new global::Gtk.EventBox();
			this.eventboxLabelCalculator.Name = "eventboxLabelCalculator";
			// Container child eventboxLabelCalculator.Gtk.Container+ContainerChild
			this.alignmentLabelCalculator = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignmentLabelCalculator.Name = "alignmentLabelCalculator";
			// Container child alignmentLabelCalculator.Gtk.Container+ContainerChild
			this.labelCalculator = new global::Gtk.Label();
			this.labelCalculator.Name = "labelCalculator";
			this.labelCalculator.LabelProp = global::Mono.Unix.Catalog.GetString("Calculator");
			this.alignmentLabelCalculator.Add(this.labelCalculator);
			this.eventboxLabelCalculator.Add(this.alignmentLabelCalculator);
			this.vboxMain.Add(this.eventboxLabelCalculator);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vboxMain[this.eventboxLabelCalculator]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vboxMain.Gtk.Box+BoxChild
			this.hboxMiddle = new global::Gtk.HBox();
			this.hboxMiddle.Name = "hboxMiddle";
			this.hboxMiddle.Spacing = 6;
			// Container child hboxMiddle.Gtk.Box+BoxChild
			this.vboxEntry = new global::Gtk.VBox();
			this.vboxEntry.Name = "vboxEntry";
			this.vboxEntry.Spacing = 6;
			// Container child vboxEntry.Gtk.Box+BoxChild
			this.labelEntry = new global::Gtk.Label();
			this.labelEntry.Name = "labelEntry";
			this.labelEntry.LabelProp = global::Mono.Unix.Catalog.GetString("Number of cases:");
			this.vboxEntry.Add(this.labelEntry);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vboxEntry[this.labelEntry]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vboxEntry.Gtk.Box+BoxChild
			this.eventboxEntry = new global::Gtk.EventBox();
			this.eventboxEntry.Name = "eventboxEntry";
			// Container child eventboxEntry.Gtk.Container+ContainerChild
			this.entryCaseNumber = new global::Gtk.Entry();
			this.entryCaseNumber.CanFocus = true;
			this.entryCaseNumber.Name = "entryCaseNumber";
			this.entryCaseNumber.IsEditable = true;
			this.entryCaseNumber.InvisibleChar = '●';
			this.eventboxEntry.Add(this.entryCaseNumber);
			this.vboxEntry.Add(this.eventboxEntry);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vboxEntry[this.eventboxEntry]));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vboxEntry.Gtk.Box+BoxChild
			this.eventboxButtonCalculate = new global::Gtk.EventBox();
			this.eventboxButtonCalculate.Name = "eventboxButtonCalculate";
			// Container child eventboxButtonCalculate.Gtk.Container+ContainerChild
			this.buttonCalculate = new global::Gtk.Button();
			this.buttonCalculate.CanFocus = true;
			this.buttonCalculate.Name = "buttonCalculate";
			this.buttonCalculate.UseUnderline = true;
			this.buttonCalculate.Label = global::Mono.Unix.Catalog.GetString("Calculate");
			this.eventboxButtonCalculate.Add(this.buttonCalculate);
			this.vboxEntry.Add(this.eventboxButtonCalculate);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vboxEntry[this.eventboxButtonCalculate]));
			w8.Position = 2;
			w8.Expand = false;
			w8.Fill = false;
			this.hboxMiddle.Add(this.vboxEntry);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hboxMiddle[this.vboxEntry]));
			w9.Position = 0;
			w9.Expand = false;
			w9.Fill = false;
			// Container child hboxMiddle.Gtk.Box+BoxChild
			this.eventboxRatios = new global::Gtk.EventBox();
			this.eventboxRatios.Name = "eventboxRatios";
			// Container child eventboxRatios.Gtk.Container+ContainerChild
			this.vboxRatios = new global::Gtk.VBox();
			this.vboxRatios.Name = "vboxRatios";
			this.vboxRatios.Spacing = 6;
			// Container child vboxRatios.Gtk.Box+BoxChild
			this.alignmentButtonRatios = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignmentButtonRatios.Name = "alignmentButtonRatios";
			// Container child alignmentButtonRatios.Gtk.Container+ContainerChild
			this.eventboxButtonRatios = new global::Gtk.EventBox();
			this.eventboxButtonRatios.Name = "eventboxButtonRatios";
			// Container child eventboxButtonRatios.Gtk.Container+ContainerChild
			this.buttonRatios = new global::Gtk.Button();
			this.buttonRatios.CanFocus = true;
			this.buttonRatios.Name = "buttonRatios";
			this.buttonRatios.UseUnderline = true;
			this.buttonRatios.Label = global::Mono.Unix.Catalog.GetString("Show ratios");
			this.eventboxButtonRatios.Add(this.buttonRatios);
			this.alignmentButtonRatios.Add(this.eventboxButtonRatios);
			this.vboxRatios.Add(this.alignmentButtonRatios);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vboxRatios[this.alignmentButtonRatios]));
			w12.Position = 0;
			w12.Expand = false;
			w12.Fill = false;
			// Container child vboxRatios.Gtk.Box+BoxChild
			this.tableRatios = new global::Gtk.Table(((uint)(2)), ((uint)(2)), false);
			this.tableRatios.Name = "tableRatios";
			this.tableRatios.RowSpacing = ((uint)(6));
			this.tableRatios.ColumnSpacing = ((uint)(6));
			// Container child tableRatios.Gtk.Table+TableChild
			this.eventboxLabelBatch = new global::Gtk.EventBox();
			this.eventboxLabelBatch.Name = "eventboxLabelBatch";
			// Container child eventboxLabelBatch.Gtk.Container+ContainerChild
			this.labelBatch = new global::Gtk.Label();
			this.labelBatch.Name = "labelBatch";
			this.labelBatch.LabelProp = global::Mono.Unix.Catalog.GetString("Batch");
			this.eventboxLabelBatch.Add(this.labelBatch);
			this.tableRatios.Add(this.eventboxLabelBatch);
			global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.tableRatios[this.eventboxLabelBatch]));
			w14.TopAttach = ((uint)(1));
			w14.BottomAttach = ((uint)(2));
			w14.XOptions = ((global::Gtk.AttachOptions)(4));
			w14.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tableRatios.Gtk.Table+TableChild
			this.eventboxLabelDough = new global::Gtk.EventBox();
			this.eventboxLabelDough.Name = "eventboxLabelDough";
			// Container child eventboxLabelDough.Gtk.Container+ContainerChild
			this.labelDough = new global::Gtk.Label();
			this.labelDough.Name = "labelDough";
			this.labelDough.LabelProp = global::Mono.Unix.Catalog.GetString("Dough");
			this.eventboxLabelDough.Add(this.labelDough);
			this.tableRatios.Add(this.eventboxLabelDough);
			global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.tableRatios[this.eventboxLabelDough]));
			w16.XOptions = ((global::Gtk.AttachOptions)(4));
			w16.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tableRatios.Gtk.Table+TableChild
			this.eventboxLabelFilling = new global::Gtk.EventBox();
			this.eventboxLabelFilling.Name = "eventboxLabelFilling";
			// Container child eventboxLabelFilling.Gtk.Container+ContainerChild
			this.labelFilling = new global::Gtk.Label();
			this.labelFilling.Name = "labelFilling";
			this.labelFilling.LabelProp = global::Mono.Unix.Catalog.GetString("Filling");
			this.eventboxLabelFilling.Add(this.labelFilling);
			this.tableRatios.Add(this.eventboxLabelFilling);
			global::Gtk.Table.TableChild w18 = ((global::Gtk.Table.TableChild)(this.tableRatios[this.eventboxLabelFilling]));
			w18.LeftAttach = ((uint)(1));
			w18.RightAttach = ((uint)(2));
			w18.XOptions = ((global::Gtk.AttachOptions)(4));
			w18.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tableRatios.Gtk.Table+TableChild
			this.eventboxLabelPaste = new global::Gtk.EventBox();
			this.eventboxLabelPaste.Name = "eventboxLabelPaste";
			// Container child eventboxLabelPaste.Gtk.Container+ContainerChild
			this.labelPaste = new global::Gtk.Label();
			this.labelPaste.Name = "labelPaste";
			this.labelPaste.LabelProp = global::Mono.Unix.Catalog.GetString("Paste");
			this.eventboxLabelPaste.Add(this.labelPaste);
			this.tableRatios.Add(this.eventboxLabelPaste);
			global::Gtk.Table.TableChild w20 = ((global::Gtk.Table.TableChild)(this.tableRatios[this.eventboxLabelPaste]));
			w20.TopAttach = ((uint)(1));
			w20.BottomAttach = ((uint)(2));
			w20.LeftAttach = ((uint)(1));
			w20.RightAttach = ((uint)(2));
			w20.XOptions = ((global::Gtk.AttachOptions)(4));
			w20.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vboxRatios.Add(this.tableRatios);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vboxRatios[this.tableRatios]));
			w21.Position = 1;
			w21.Expand = false;
			w21.Fill = false;
			this.eventboxRatios.Add(this.vboxRatios);
			this.hboxMiddle.Add(this.eventboxRatios);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hboxMiddle[this.eventboxRatios]));
			w23.Position = 1;
			w23.Expand = false;
			w23.Fill = false;
			this.vboxMain.Add(this.hboxMiddle);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.vboxMain[this.hboxMiddle]));
			w24.Position = 1;
			w24.Expand = false;
			w24.Fill = false;
			// Container child vboxMain.Gtk.Box+BoxChild
			this.eventboxBottom = new global::Gtk.EventBox();
			this.eventboxBottom.Name = "eventboxBottom";
			// Container child eventboxBottom.Gtk.Container+ContainerChild
			this.vbox7 = new global::Gtk.VBox();
			this.vbox7.Name = "vbox7";
			this.vbox7.Spacing = 6;
			// Container child vbox7.Gtk.Box+BoxChild
			this.labelResult = new global::Gtk.Label();
			this.labelResult.Name = "labelResult";
			this.labelResult.LabelProp = global::Mono.Unix.Catalog.GetString("Results");
			this.vbox7.Add(this.labelResult);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.labelResult]));
			w25.Position = 0;
			w25.Expand = false;
			w25.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.tableResults = new global::Gtk.Table(((uint)(4)), ((uint)(2)), false);
			this.tableResults.Name = "tableResults";
			this.tableResults.RowSpacing = ((uint)(6));
			this.tableResults.ColumnSpacing = ((uint)(6));
			this.tableResults.BorderWidth = ((uint)(2));
			// Container child tableResults.Gtk.Table+TableChild
			this.eventbox24 = new global::Gtk.EventBox();
			this.eventbox24.Name = "eventbox24";
			// Container child eventbox24.Gtk.Container+ContainerChild
			this.label13 = new global::Gtk.Label();
			this.label13.Name = "label13";
			this.label13.Xpad = 5;
			this.label13.LabelProp = global::Mono.Unix.Catalog.GetString("Dough Batches");
			this.eventbox24.Add(this.label13);
			this.tableResults.Add(this.eventbox24);
			global::Gtk.Table.TableChild w27 = ((global::Gtk.Table.TableChild)(this.tableResults[this.eventbox24]));
			w27.XOptions = ((global::Gtk.AttachOptions)(4));
			w27.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tableResults.Gtk.Table+TableChild
			this.eventbox26 = new global::Gtk.EventBox();
			this.eventbox26.Name = "eventbox26";
			// Container child eventbox26.Gtk.Container+ContainerChild
			this.label14 = new global::Gtk.Label();
			this.label14.Name = "label14";
			this.label14.Xpad = 5;
			this.label14.LabelProp = global::Mono.Unix.Catalog.GetString("Chicken (oz)");
			this.eventbox26.Add(this.label14);
			this.tableResults.Add(this.eventbox26);
			global::Gtk.Table.TableChild w29 = ((global::Gtk.Table.TableChild)(this.tableResults[this.eventbox26]));
			w29.TopAttach = ((uint)(1));
			w29.BottomAttach = ((uint)(2));
			w29.XOptions = ((global::Gtk.AttachOptions)(4));
			w29.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tableResults.Gtk.Table+TableChild
			this.eventbox28 = new global::Gtk.EventBox();
			this.eventbox28.Name = "eventbox28";
			// Container child eventbox28.Gtk.Container+ContainerChild
			this.label15 = new global::Gtk.Label();
			this.label15.Name = "label15";
			this.label15.Xpad = 5;
			this.label15.LabelProp = global::Mono.Unix.Catalog.GetString("Cream Cheese");
			this.eventbox28.Add(this.label15);
			this.tableResults.Add(this.eventbox28);
			global::Gtk.Table.TableChild w31 = ((global::Gtk.Table.TableChild)(this.tableResults[this.eventbox28]));
			w31.TopAttach = ((uint)(2));
			w31.BottomAttach = ((uint)(3));
			w31.XOptions = ((global::Gtk.AttachOptions)(4));
			w31.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tableResults.Gtk.Table+TableChild
			this.eventbox30 = new global::Gtk.EventBox();
			this.eventbox30.Name = "eventbox30";
			// Container child eventbox30.Gtk.Container+ContainerChild
			this.label16 = new global::Gtk.Label();
			this.label16.Name = "label16";
			this.label16.Xpad = 5;
			this.label16.LabelProp = global::Mono.Unix.Catalog.GetString("Shredded Cheese");
			this.eventbox30.Add(this.label16);
			this.tableResults.Add(this.eventbox30);
			global::Gtk.Table.TableChild w33 = ((global::Gtk.Table.TableChild)(this.tableResults[this.eventbox30]));
			w33.TopAttach = ((uint)(3));
			w33.BottomAttach = ((uint)(4));
			w33.XOptions = ((global::Gtk.AttachOptions)(4));
			w33.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tableResults.Gtk.Table+TableChild
			this.eventbox32 = new global::Gtk.EventBox();
			this.eventbox32.Name = "eventbox32";
			// Container child eventbox32.Gtk.Container+ContainerChild
			this.labelDoughBatchResult = new global::Gtk.Label();
			this.labelDoughBatchResult.Name = "labelDoughBatchResult";
			this.labelDoughBatchResult.LabelProp = global::Mono.Unix.Catalog.GetString("     ");
			this.eventbox32.Add(this.labelDoughBatchResult);
			this.tableResults.Add(this.eventbox32);
			global::Gtk.Table.TableChild w35 = ((global::Gtk.Table.TableChild)(this.tableResults[this.eventbox32]));
			w35.LeftAttach = ((uint)(1));
			w35.RightAttach = ((uint)(2));
			w35.XOptions = ((global::Gtk.AttachOptions)(4));
			w35.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tableResults.Gtk.Table+TableChild
			this.eventbox34 = new global::Gtk.EventBox();
			this.eventbox34.Name = "eventbox34";
			// Container child eventbox34.Gtk.Container+ContainerChild
			this.labelChickenResult = new global::Gtk.Label();
			this.labelChickenResult.Name = "labelChickenResult";
			this.labelChickenResult.LabelProp = global::Mono.Unix.Catalog.GetString("     ");
			this.eventbox34.Add(this.labelChickenResult);
			this.tableResults.Add(this.eventbox34);
			global::Gtk.Table.TableChild w37 = ((global::Gtk.Table.TableChild)(this.tableResults[this.eventbox34]));
			w37.TopAttach = ((uint)(1));
			w37.BottomAttach = ((uint)(2));
			w37.LeftAttach = ((uint)(1));
			w37.RightAttach = ((uint)(2));
			w37.XOptions = ((global::Gtk.AttachOptions)(4));
			w37.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tableResults.Gtk.Table+TableChild
			this.eventbox36 = new global::Gtk.EventBox();
			this.eventbox36.Name = "eventbox36";
			// Container child eventbox36.Gtk.Container+ContainerChild
			this.labelCreamCheeseResult = new global::Gtk.Label();
			this.labelCreamCheeseResult.Name = "labelCreamCheeseResult";
			this.labelCreamCheeseResult.LabelProp = global::Mono.Unix.Catalog.GetString("     ");
			this.eventbox36.Add(this.labelCreamCheeseResult);
			this.tableResults.Add(this.eventbox36);
			global::Gtk.Table.TableChild w39 = ((global::Gtk.Table.TableChild)(this.tableResults[this.eventbox36]));
			w39.TopAttach = ((uint)(2));
			w39.BottomAttach = ((uint)(3));
			w39.LeftAttach = ((uint)(1));
			w39.RightAttach = ((uint)(2));
			w39.XOptions = ((global::Gtk.AttachOptions)(4));
			w39.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tableResults.Gtk.Table+TableChild
			this.eventbox38 = new global::Gtk.EventBox();
			this.eventbox38.Name = "eventbox38";
			// Container child eventbox38.Gtk.Container+ContainerChild
			this.labelShreddedCheeseResult = new global::Gtk.Label();
			this.labelShreddedCheeseResult.Name = "labelShreddedCheeseResult";
			this.labelShreddedCheeseResult.LabelProp = global::Mono.Unix.Catalog.GetString("     ");
			this.eventbox38.Add(this.labelShreddedCheeseResult);
			this.tableResults.Add(this.eventbox38);
			global::Gtk.Table.TableChild w41 = ((global::Gtk.Table.TableChild)(this.tableResults[this.eventbox38]));
			w41.TopAttach = ((uint)(3));
			w41.BottomAttach = ((uint)(4));
			w41.LeftAttach = ((uint)(1));
			w41.RightAttach = ((uint)(2));
			w41.XOptions = ((global::Gtk.AttachOptions)(4));
			w41.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vbox7.Add(this.tableResults);
			global::Gtk.Box.BoxChild w42 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.tableResults]));
			w42.Position = 1;
			w42.Expand = false;
			w42.Fill = false;
			this.eventboxBottom.Add(this.vbox7);
			this.vboxMain.Add(this.eventboxBottom);
			global::Gtk.Box.BoxChild w44 = ((global::Gtk.Box.BoxChild)(this.vboxMain[this.eventboxBottom]));
			w44.Position = 2;
			w44.Expand = false;
			w44.Fill = false;
			// Container child vboxMain.Gtk.Box+BoxChild
			this.eventboxNavigation = new global::Gtk.EventBox();
			this.eventboxNavigation.Name = "eventboxNavigation";
			// Container child eventboxNavigation.Gtk.Container+ContainerChild
			this.hboxNavigation = new global::Gtk.HBox();
			this.hboxNavigation.Name = "hboxNavigation";
			this.hboxNavigation.Spacing = 6;
			// Container child hboxNavigation.Gtk.Box+BoxChild
			this.eventboxButtonHome = new global::Gtk.EventBox();
			this.eventboxButtonHome.Name = "eventboxButtonHome";
			// Container child eventboxButtonHome.Gtk.Container+ContainerChild
			this.buttonHome = new global::Gtk.Button();
			this.buttonHome.CanFocus = true;
			this.buttonHome.Name = "buttonHome";
			this.buttonHome.UseUnderline = true;
			this.buttonHome.Label = global::Mono.Unix.Catalog.GetString("Home");
			this.eventboxButtonHome.Add(this.buttonHome);
			this.hboxNavigation.Add(this.eventboxButtonHome);
			global::Gtk.Box.BoxChild w46 = ((global::Gtk.Box.BoxChild)(this.hboxNavigation[this.eventboxButtonHome]));
			w46.Position = 0;
			w46.Expand = false;
			w46.Fill = false;
			this.eventboxNavigation.Add(this.hboxNavigation);
			this.vboxMain.Add(this.eventboxNavigation);
			global::Gtk.Box.BoxChild w48 = ((global::Gtk.Box.BoxChild)(this.vboxMain[this.eventboxNavigation]));
			w48.Position = 3;
			w48.Expand = false;
			w48.Fill = false;
			this.eventboxMain.Add(this.vboxMain);
			this.Add(this.eventboxMain);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
			this.buttonCalculate.Clicked += new global::System.EventHandler(this.OnButtonCalculateClicked);
			this.buttonRatios.Clicked += new global::System.EventHandler(this.OnButtonRatiosClicked);
			this.buttonHome.Clicked += new global::System.EventHandler(this.OnButtonHomeClicked);
		}
	}
}
