
// This file has been generated by the GUI designer. Do not modify.
namespace BakeryApplication
{
	public partial class Page
	{
		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget BakeryApplication.Page
			global::Stetic.BinContainer.Attach(this);
			this.Name = "BakeryApplication.Page";
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
		}
	}
}
