
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.EventBox eventboxMain;

	private global::Gtk.VBox vboxMain;

	private global::Gtk.EventBox eventboxLabels;

	private global::Gtk.HBox hbox3;

	private global::Gtk.Label labelDatetime;

	private global::Gtk.Notebook notebookPages;

	private global::BakeryApplication.HomePage homepage1;

	private global::Gtk.Label labelHomePage;

	private global::BakeryApplication.CalculatorPage calculatorpage1;

	private global::Gtk.Label labelCalculatorPage;

	private global::BakeryApplication.InventoryPage inventorypage1;

	private global::Gtk.Label labelInventoryPage;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.eventboxMain = new global::Gtk.EventBox();
		this.eventboxMain.Name = "eventboxMain";
		// Container child eventboxMain.Gtk.Container+ContainerChild
		this.vboxMain = new global::Gtk.VBox();
		this.vboxMain.Name = "vboxMain";
		this.vboxMain.Spacing = 6;
		// Container child vboxMain.Gtk.Box+BoxChild
		this.eventboxLabels = new global::Gtk.EventBox();
		this.eventboxLabels.Name = "eventboxLabels";
		// Container child eventboxLabels.Gtk.Container+ContainerChild
		this.hbox3 = new global::Gtk.HBox();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.labelDatetime = new global::Gtk.Label();
		this.labelDatetime.Name = "labelDatetime";
		this.labelDatetime.Xalign = 1F;
		this.labelDatetime.LabelProp = global::Mono.Unix.Catalog.GetString("Datetime");
		this.hbox3.Add(this.labelDatetime);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.labelDatetime]));
		w1.Position = 2;
		w1.Expand = false;
		w1.Fill = false;
		this.eventboxLabels.Add(this.hbox3);
		this.vboxMain.Add(this.eventboxLabels);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vboxMain[this.eventboxLabels]));
		w3.Position = 0;
		w3.Expand = false;
		w3.Fill = false;
		// Container child vboxMain.Gtk.Box+BoxChild
		this.notebookPages = new global::Gtk.Notebook();
		this.notebookPages.CanFocus = true;
		this.notebookPages.Name = "notebookPages";
		this.notebookPages.CurrentPage = 1;
		this.notebookPages.ShowBorder = false;
		this.notebookPages.ShowTabs = false;
		// Container child notebookPages.Gtk.Notebook+NotebookChild
		this.homepage1 = new global::BakeryApplication.HomePage();
		this.homepage1.Events = ((global::Gdk.EventMask)(256));
		this.homepage1.Name = "homepage1";
		this.notebookPages.Add(this.homepage1);
		// Notebook tab
		this.labelHomePage = new global::Gtk.Label();
		this.labelHomePage.Name = "labelHomePage";
		this.labelHomePage.LabelProp = global::Mono.Unix.Catalog.GetString("HomePage");
		this.notebookPages.SetTabLabel(this.homepage1, this.labelHomePage);
		this.labelHomePage.ShowAll();
		// Container child notebookPages.Gtk.Notebook+NotebookChild
		this.calculatorpage1 = new global::BakeryApplication.CalculatorPage();
		this.calculatorpage1.Events = ((global::Gdk.EventMask)(256));
		this.calculatorpage1.Name = "calculatorpage1";
		this.notebookPages.Add(this.calculatorpage1);
		global::Gtk.Notebook.NotebookChild w5 = ((global::Gtk.Notebook.NotebookChild)(this.notebookPages[this.calculatorpage1]));
		w5.Position = 1;
		// Notebook tab
		this.labelCalculatorPage = new global::Gtk.Label();
		this.labelCalculatorPage.Name = "labelCalculatorPage";
		this.labelCalculatorPage.LabelProp = global::Mono.Unix.Catalog.GetString("Calculator");
		this.notebookPages.SetTabLabel(this.calculatorpage1, this.labelCalculatorPage);
		this.labelCalculatorPage.ShowAll();
		// Container child notebookPages.Gtk.Notebook+NotebookChild
		this.inventorypage1 = new global::BakeryApplication.InventoryPage();
		this.inventorypage1.Events = ((global::Gdk.EventMask)(256));
		this.inventorypage1.Name = "inventorypage1";
		this.notebookPages.Add(this.inventorypage1);
		global::Gtk.Notebook.NotebookChild w6 = ((global::Gtk.Notebook.NotebookChild)(this.notebookPages[this.inventorypage1]));
		w6.Position = 2;
		// Notebook tab
		this.labelInventoryPage = new global::Gtk.Label();
		this.labelInventoryPage.Name = "labelInventoryPage";
		this.labelInventoryPage.LabelProp = global::Mono.Unix.Catalog.GetString("Inventory");
		this.notebookPages.SetTabLabel(this.inventorypage1, this.labelInventoryPage);
		this.labelInventoryPage.ShowAll();
		this.vboxMain.Add(this.notebookPages);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vboxMain[this.notebookPages]));
		w7.Position = 1;
		this.eventboxMain.Add(this.vboxMain);
		this.Add(this.eventboxMain);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 666;
		this.DefaultHeight = 376;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
	}
}
